import { FaGoogle, FaGithub, FaFacebookF, FaLinkedinIn, FaInstagram, FaWhatsapp, FaRegUser } from "react-icons/fa";
import { FaXTwitter } from "react-icons/fa6";
import {
  Home,
  Users,
  LineChart,
  Mail,
  Workflow,
  Database,
  Palette,
  Rocket,
  Settings,
  Package,
  Files,
  LucideIcon,
  Loader2,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  ChevronsUpDown,
  Code,
  Play,
  Image,
  Music,
  File,
  Frame,
  Video,
  Square,
  Type,
  Minus,
  ArrowUpDown,
  FileText,
  FolderGit2,
  Grid,
  LayoutGrid,
  PanelLeft,
  PanelLeftClose,
  LayoutPanelTop,
  Lock,
  LockKeyhole,
  Plus,
  Search,
  Ban,
  Star,
  Heart,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ArrowLeftCircle,
  Check,
  CheckCircle,
  CheckCircle2,
  CheckSquare,
  X,
  Phone,
  MapPin,
  Calendar,
  CalendarDays,
  Clock,
  User,
  Bell,
  BellIcon,
  Folder,
  Download,
  Upload,
  ExternalLink,
  Link,
  Bookmark,
  Save,
  Trash,
  Trash2,
  Pencil,
  Edit,
  Share,
  Info,
  AlertCircle,
  AlertTriangle,
  XCircle,
  Hash,
  List,
  ListChecks,
  ListOrdered,
  Circle,
  AlignLeft,
  TextIcon,
  ShapesIcon,
  Radio,
  MessageCircle,
  MoreHorizontal,
  Eye,
  EyeIcon,
  Copy,
  FormInput,
  Flag,
  RefreshCw,
  Shield,
  Moon,
  Sun,
  LogOutIcon,
  Package2Icon,
  BookOpen,
  Cog,
} from "lucide-react";

export type Icon = LucideIcon | React.ComponentType<any>;

export const Icons = {
  // Legacy named icons (keeping for backward compatibility)
  HomeIcon: Home,
  UsersIcon: Users,
  LineChartIcon: LineChart,
  PackageIcon: Package,
  EnvelopeClosedIcon: Mail,
  FilesIcon: Files,
  WorkflowIcon: Workflow,
  DatabaseIcon: Database,
  PaletteIcon: Palette,
  RocketIcon: Rocket,
  SettingsIcon: Settings,
  GitHubIcon: FaGithub,
  GoogleIcon: FaGoogle,
  SpinnerIcon: Loader2,
  
  // Navigation & Layout
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  ChevronsUpDown,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ArrowLeftCircle,
  ArrowUpDown,
  PanelLeft,
  PanelLeftClose,
  LayoutPanelTop,
  MoreHorizontal,
  
  // Content & Media
  Code,
  Play,
  Image,
  Music,
  File,
  FileText,
  Frame,
  Video,
  Square,
  Type,
  TextIcon,
  ShapesIcon,
  BookOpen,
  EyeIcon,
  Eye,
  
  // Actions
  Plus,
  Minus,
  Search,
  Ban,
  Check,
  CheckCircle,
  CheckCircle2,
  CheckSquare,
  X,
  Copy,
  Download,
  Upload,
  ExternalLink,
  Link,
  Save,
  Trash,
  Trash2,
  Edit,
  Pencil,
  Share,
  Flag,
  RefreshCw,
  
  // User & Social
  User,
  Users,
  FaRegUser,
  Bell,
  BellIcon,
  Star,
  Heart,
  Bookmark,
  Settings,
  Cog,
  Lock,
  LockKeyhole,
  Shield,
  LogOutIcon,
  
  // Social Media
  FaGoogle: FaGoogle,
  FaGithub: FaGithub,
  FaFacebookF: FaFacebookF,
  FaLinkedinIn: FaLinkedinIn,
  FaXTwitter: FaXTwitter,
  FaInstagram: FaInstagram,
  FaWhatsapp: FaWhatsapp,
  
  // Communication & Contact
  Mail,
  Phone,
  MapPin,
  Calendar,
  CalendarDays,
  Clock,
  MessageCircle,
  
  // Status & Notifications
  Info,
  AlertCircle,
  AlertTriangle,
  XCircle,
  
  // Organization & Structure
  Home,
  Folder,
  FolderGit2,
  Package,
  Package2Icon,
  Files,
  Grid,
  LayoutGrid,
  List,
  ListChecks,
  ListOrdered,
  Hash,
  Circle,
  AlignLeft,
  
  // Forms
  FormInput,
  Radio,
  
  // Theme & UI
  Moon,
  Sun,
  Loader2,
  
  // Business & Analytics
  LineChart,
  Workflow,
  Database,
  Palette,
  Rocket,
} as const;

export type IconKeys = keyof typeof Icons;

// Icon categories for organized usage
export const iconCategories = {
  Navegación: [
    "ChevronDown", "ChevronUp", "ChevronLeft", "ChevronRight", "ArrowRight", "ArrowLeft", 
    "ArrowUp", "ArrowDown", "ExternalLink", "Link", "PanelLeft"
  ],
  Acciones: [
    "Plus", "Minus", "Check", "X", "Download", "Upload", "Save", "Trash", "Trash2", 
    "Edit", "Pencil", "Share", "Copy", "RefreshCw"
  ],
  Usuario: [
    "User", "Users", "Settings", "Star", "Heart", "Bookmark", "Lock", "Shield", "LogOutIcon"
  ],
  Contenido: [
    "File", "FileText", "Image", "Video", "Music", "Code", "BookOpen", "Eye"
  ],
  Comunicación: [
    "Mail", "Phone", "MapPin", "Calendar", "Clock", "MessageCircle"
  ],
  Estado: [
    "Bell", "Info", "AlertCircle", "AlertTriangle", "CheckCircle", "XCircle"
  ],
  Social: [
    "FaGoogle", "FaGithub", "FaFacebookF", "FaLinkedinIn", "FaXTwitter", "FaInstagram", "FaWhatsapp"
  ]
} as const;
