export const invitedUsers = [
  { email: "info@insidesalons.com", responseStatus: "accepted" },
  { email: "gestion@insidesalons.com", responseStatus: "accepted" },
  { email: "marketing@insidesalons.com", responseStatus: "needsAction" },
  { email: "bernat@insidesalons.com", responseStatus: "accepted" },
  { email: "alvaro@insidesalons.com", responseStatus: "accepted" },
  { email: "patricia@insidesalons.com", responseStatus: "needsAction" },
  { email: "sistemas@insidesalons.com", responseStatus: "accepted" },
  { email: "lorena@insidesalons.com", responseStatus: "declined" },
  { email: "pedro@insidesalons.com", responseStatus: "accepted" },
  { email: "carlos@insidesalons.com", responseStatus: "needsAction" },
  { email: "noemi@insidesalons.com", responseStatus: "accepted" },
  { email: "leonel@insidesalons.com", responseStatus: "accepted" },
  { email: "lola.gimeno@insidesalons.com", responseStatus: "needsAction" },
  { email: "judit@insidesalons.com", responseStatus: "accepted" },
  { email: "joana@insidesalons.com", responseStatus: "declined" },
  { email: "hernan@insidesalons.com", responseStatus: "accepted" },
  { email: "miguel@insidesalons.com", responseStatus: "needsAction" },
];
